# Generated by Django 2.2.9 on 2020-06-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200628_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('banner', models.ImageField(upload_to='event-imgs')),
                ('price', models.IntegerField()),
                ('extra_price', models.CharField(max_length=200)),
                ('text_1', models.TextField()),
                ('text_2', models.TextField()),
                ('text_3', models.TextField()),
                ('text_4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('president', 'president'), ('vice president 1', 'vice president 1'), ('vice president 2', 'vice president 2'), ('multimedia director', 'multimedia director')], max_length=50)),
                ('season', models.IntegerField()),
                ('img', models.ImageField(upload_to='members-imgs')),
            ],
        ),
    ]
