# Generated by Django 2.2.9 on 2020-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_events_previous_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='extra_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
