# Generated by Django 2.2.9 on 2020-06-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_event_reservation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reservation',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
