# Generated by Django 2.2.9 on 2020-08-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200628_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='album_cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('text', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to='album-cover')),
            ],
        ),
    ]
