# Generated by Django 2.2.9 on 2020-08-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_album_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='images_in_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img-in-album')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.album_cover')),
            ],
        ),
    ]
