# Generated by Django 2.2.9 on 2020-08-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_images_in_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_in_album',
            name='img',
            field=models.FileField(upload_to='img-in-album'),
        ),
    ]
