# Generated by Django 2.2.9 on 2020-08-06 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200806_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_in_album',
            name='img',
            field=models.ImageField(upload_to='img-in-album'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img-in-album')),
                ('iia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.images_in_album')),
            ],
        ),
    ]
