# Generated by Django 2.2.9 on 2020-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200807_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Engineering', 'Engineering')], max_length=50)),
                ('first_prefrence', models.CharField(choices=[('multimedia', 'multimedia'), ('hr', 'hr'), ('er', 'er'), ('presentation', 'presentation'), ('project', 'project')], max_length=50)),
                ('second_prefrence', models.CharField(choices=[('multimedia', 'multimedia'), ('hr', 'hr'), ('er', 'er'), ('presentation', 'presentation'), ('project', 'project')], max_length=50)),
            ],
        ),
    ]
