# Generated by Django 2.2.9 on 2020-08-07 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200807_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
