# Generated by Django 2.2.9 on 2020-08-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_event_reservation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_reservation',
            name='created_at',
        ),
    ]
