# Generated by Django 2.2.9 on 2020-08-07 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_event_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 19, 30, 45, 392830)),
        ),
    ]
