# Generated by Django 2.2.9 on 2020-08-07 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_event_reservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 7, 19, 36, 32, 754359)),
        ),
    ]
