# Generated by Django 2.2.9 on 2020-08-07 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200807_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='is_recruitment',
            new_name='open_recruitment',
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 7, 22, 16, 9, 860082)),
        ),
    ]
