# Generated by Django 2.2.9 on 2020-08-07 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200807_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('qr_img', models.ImageField(blank=True, null=True, upload_to='qr-imgs')),
            ],
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 7, 23, 26, 36, 381945)),
        ),
    ]
