# Generated by Django 2.2.9 on 2020-08-07 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200807_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='title',
            field=models.CharField(default='QR Code for Enactus NCA APP', max_length=100),
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 7, 23, 28, 28, 427307)),
        ),
    ]
