# Generated by Django 2.2.9 on 2020-08-08 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20200808_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 8, 13, 58, 44, 764289)),
        ),
    ]
