# Generated by Django 2.2.9 on 2020-08-08 11:59

import datetime
from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200808_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 8, 13, 59, 28, 788998)),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='season',
            field=models.IntegerField(default=website.models.recruitment.current_year, verbose_name='year'),
        ),
    ]
