# Generated by Django 2.2.9 on 2020-08-12 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20200808_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 12, 18, 17, 6, 994168)),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='season',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 12, 18, 17, 6, 994168)),
        ),
    ]
