# Generated by Django 2.2.9 on 2020-08-18 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20200813_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='year_of_study',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 18, 13, 5, 1, 518801)),
        ),
    ]
