# Generated by Django 2.2.9 on 2020-09-05 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20200818_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='season',
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 21, 46, 41, 501188)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 21, 46, 41, 516810)),
        ),
    ]
