# Generated by Django 2.2.9 on 2020-09-05 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20200905_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 23, 10, 7, 97186)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 23, 10, 7, 107306)),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='season',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 23, 10, 7, 105264)),
        ),
    ]
