# Generated by Django 2.2.9 on 2020-09-05 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20200905_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='season',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 23, 12, 57, 495115)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 23, 12, 57, 510743)),
        ),
    ]
