# Generated by Django 2.2.9 on 2020-09-05 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20200905_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 23, 16, 1, 603641)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 5, 23, 16, 1, 619245)),
        ),
    ]
