# Generated by Django 2.2.9 on 2020-09-10 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20200905_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 10, 7, 44, 49, 830663)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 10, 7, 44, 49, 846258)),
        ),
    ]
