# Generated by Django 2.2.9 on 2020-09-10 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_auto_20200910_0744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='img',
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 10, 9, 24, 43, 733156)),
        ),
    ]
