# Generated by Django 2.2.9 on 2020-09-10 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20200910_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='sponser-imgs')),
            ],
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 10, 9, 53, 7, 758785)),
        ),
    ]
