# Generated by Django 2.2.9 on 2020-09-11 03:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20200910_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='summary-imgs'),
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 11, 5, 31, 34, 960452)),
        ),
        migrations.CreateModel(
            name='all_seasons_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('president', models.CharField(max_length=50)),
                ('president_img', models.ImageField(upload_to='all-seasons-board-imgs')),
                ('vice_1', models.CharField(max_length=50)),
                ('vice_1_img', models.ImageField(upload_to='all-seasons-board-imgs')),
                ('vice_2', models.CharField(max_length=50)),
                ('vice_2_img', models.ImageField(upload_to='all-seasons-board-imgs')),
                ('multimedia', models.CharField(max_length=50)),
                ('multimedia_img', models.ImageField(upload_to='all-seasons-board-imgs')),
                ('hr', models.CharField(max_length=50)),
                ('hr_img', models.ImageField(upload_to='all-seasons-board-imgs')),
                ('er', models.CharField(max_length=50)),
                ('er_img', models.ImageField(upload_to='all-seasons-board-imgs')),
                ('project', models.CharField(max_length=50)),
                ('project_img', models.ImageField(upload_to='all-seasons-board-imgs')),
                ('presentation', models.CharField(max_length=50)),
                ('presentation_img', models.ImageField(upload_to='all-seasons-board-imgs')),
                ('summary_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.summary')),
            ],
        ),
    ]
