# Generated by Django 2.2.9 on 2020-09-11 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20200911_0531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='event',
            name='banner',
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 11, 12, 46, 23, 197029)),
        ),
    ]
