# Generated by Django 2.2.9 on 2020-09-12 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_auto_20200911_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('text', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to='album-cover')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(default=1, upload_to='event-imgs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 12, 23, 28, 17, 909124)),
        ),
    ]
