# Generated by Django 2.2.9 on 2020-10-10 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20200911_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_seasons_board',
            name='vice_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='all_seasons_board',
            name='vice_3_img',
            field=models.ImageField(blank=True, null=True, upload_to='all-seasons-board-imgs'),
        ),
    ]
