# Generated by Django 2.2.9 on 2020-11-16 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_auto_20201010_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_reservation',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_reservation',
            name='first_time_for_him',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event_reservation',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event_reservation',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 16, 20, 33, 47, 675200)),
        ),
        migrations.AlterField(
            model_name='season_board_1',
            name='role',
            field=models.CharField(choices=[('president', 'president'), ('vice president 1', 'vice president 1'), ('vice president 2', 'vice president 2'), ('vice president 3', 'vice president 3'), ('multimedia director', 'multimedia director'), ('er director', 'ER director'), ('hr director', 'HR director'), ('project director', 'project director'), ('presentation director', 'presentation director')], max_length=50),
        ),
        migrations.AlterField(
            model_name='season_board_2',
            name='role',
            field=models.CharField(choices=[('president', 'president'), ('vice president 1', 'vice president 1'), ('vice president 2', 'vice president 2'), ('vice president 3', 'vice president 3'), ('multimedia director', 'multimedia director'), ('er director', 'ER director'), ('hr director', 'HR director'), ('project director', 'project director'), ('presentation director', 'presentation director')], max_length=50),
        ),
    ]
